sudo: required

services:
  - docker

before_install:
  - export BUILD_ID=${TRAVIS_COMMIT::8}
  - export REPO=linagora/esn-sabre
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
  - docker build -t $REPO:$BUILD_ID .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag $REPO:$BUILD_ID $REPO:$TAG
  - docker push $REPO:$TAG

script:
  - docker images
